### ISSUE TITLE
Search field filters for campuses?

### ISSUE THREAD

**Issue by bexar** [uw-it-aca/pathways#40]
Determine if we need to let user select campus when searching for course/major

**Comment by kbui98** [comment]
![Campus Selector-Campus Unselected](https://user-images.githubusercontent.com/32370342/136114497-e9db54c4-b0a3-4df2-a0ce-02af482d1dc7.png)
![Campus Selector-Campus Selected](https://user-images.githubusercontent.com/32370342/136114519-ce329877-b7af-4f6c-bc3d-783a680165c4.png)
![Course Dropdown-Selection](https://user-images.githubusercontent.com/32370342/136114529-8d5825d7-53c6-4eaf-90e0-53224748845a.png)

Ideal behavior would be:
- User's campus already preselected for them (ex. if they're from Bothell, Bothell will already be selected)
- On home page, major/courses dropdown is deselected
- On major page, major dropdown is selected
- On course page, course dropdown is selected
